### ISSUE TITLE
support subtraction of interior "lakes"

### ISSUE THREAD

**Issue by timhevel** [OpenStitching/lir#20]
can you add support for the subtraction of interior "lakes" or "no-go zones"
![example](https://user-images.githubusercontent.com/59701140/223082711-ddb6d4a1-ee1f-4ace-80c3-f8fbe08830f0.png)

**Comment by lukasalexanderweber** [comment]
what is your desired output? can you draw it into the image?

**Comment by timhevel** [comment]
I recreated your example but added the black rectangle (see the last post). I would want the largest possible inscribed rectangle that is not overlapping any interior polygons (like the black rectangle in the example). Is the image in the last post visible to you?

**Comment by lukasalexanderweber** [comment]
So the red `lir` in your image is the desired result? In my opinion this should also be the output of lir.lir()

**Comment by timhevel** [comment]
so lir.lir() accepts multiple polygon np arrays to create the mask? can you show me how?

**Comment by lukasalexanderweber** [comment]
ahh now I've got it you are working with contours, are you? Are you dependent on the performance boost? If you only have the binary grid as input the result should be the red `lir` as in your image.

**Comment by timhevel** [comment]
yes, I am. I'm working in millimeter precision on room scale, so that would be a grid of like 5000x8000mm. and I'm doing 10 rooms at once. so a binary grid is probably not an option

**Comment by lukasalexanderweber** [comment]
<img width="558" alt="223093490-37dfac06-00f1-401f-a049-6bf5234053b2" src="https://user-images.githubusercontent.com/32765578/223101064-dbd916a1-96d1-485f-8551-a40d60caa0a6.png">

so green should be the input contour and purple the "splitter"

**Comment by lukasalexanderweber** [comment]
I can't tell right away how the contour can be split in a suitable way. Feel free to work on it and I'm open to discuss changes based on an appropriate workflow/algorithm you found

**Comment by timhevel** [comment]
maybe use cv.fillPoly on each individual lake but with a zeroes mask of the bbox of the outer/main polygon, add all arrays of the lakes together, and then subtract the resulting array from the main mask array making all 255 cells that overlap with a lake zero again. does that make sense? 
![image](https://user-images.githubusercontent.com/59701140/223151580-8a14d991-ae36-4522-8f34-90268beacf2b.png)

**Comment by lukasalexanderweber** [comment]
I guess this won't work for the contours approach, only for a "simple" binary grid

**Comment by timhevel** [comment]
correct me if I'm wrong but create_mask_from_polygon() converts the polygon contours to a binary grid in the background right?

**Comment by lukasalexanderweber** [comment]
yes it does

**Comment by timhevel** [comment]
so why wouldn't it work for a contours approach?

**Comment by timhevel** [comment]
ah okay did not know that, would you be able to implement this and raise an exception if this occurs?

there might be a bit of pseudo-code in there, but do you think this would work?

```
def create_mask_from_polygon(polygon, lakes=None):
    assert polygon.shape[0] == 1
    assert polygon.shape[1] > 2
    assert polygon.shape[2] == 2
    check_for_opencv()
    bbox = cv.boundingRect(polygon)
    mask = np.zeros([bbox[3], bbox[2]], dtype=np.uint8)
    zero_centered_x = polygon[:, :, 0] - bbox[0]
    zero_centered_y = polygon[:, :, 1] - bbox[1]
    polygon = np.dstack((zero_centered_x, zero_centered_y))
    main_mask = cv.fillPoly(mask, polygon, 255)
    
    if lakes:
        submasks = []
        for i in lakes:
            sub_mask = cv.fillPoly(mask, i, 255)
            submasks.append(sub_mask)

        for i in submasks:
            np.subtract(main_mask, i)
    else:

    origin = bbox[0:2]
    return origin, main_mask
```

**Comment by lukasalexanderweber** [comment]
> ah okay did not know that, would you be able to implement this and raise an exception if this occurs?

There is no way to detect if the wrong `lir` is detected. I will just get the biggest `lir` touching the contour and considering the lakes (yellow):

<img width="110" alt="223363506-09f35626-c405-46eb-aaf6-d72aa8a6158a2" src="https://user-images.githubusercontent.com/32765578/223375621-655bb333-fe08-4a08-8084-a0146fdc44bb.png">

I suggest that you prepare the mask as you showed in your pseudo code. Then look if you get the desired results and what the timings are. If it works we might consider adding the lake functionality using a PR :)

**Comment by lukasalexanderweber** [comment]
another challenge is that you want to iterate over the same mask to get 3 `lir`s. In your case `n` lakes + 1

**Comment by timhevel** [comment]
not per definition lakes+1 but yea i want to divide the rooms in large rectangles. for example, an L-shaped room would have 2 rectangles but no lakes. I want the algorithm to stop once the area of the new rectangles are below a certain percentage of the area of the biggest rectangle or if they are below 1m2 or something. but yea that is for later
