### ISSUE TITLE
versions >=3.7,<3.11 are supported

### ISSUE THREAD

**Issue by yogi1510** [OpenStitching/lir#22]
while installing through pip, it is throwing error as:
`RuntimeError: Cannot install on Python version 3.11.1; only versions >=3.7,<3.11 are supported.`
can anyone suggest how to use this package on Python version 3.11.1

**Comment by lukasalexanderweber** [comment]
I think that there should shortly be `numba` support for Python 11 -> https://github.com/numba/numba/issues/8304

**Comment by lukasalexanderweber** [comment]
Python 3.11 is now supported
