### ISSUE TITLE
use this on an image that is a mask

### ISSUE THREAD

**Issue by srini8080** [OpenStitching/lir#30]
How do I code it to use it on an image xyz.png?
![151_bb](https://github.com/OpenStitching/lir/assets/12046302/39d63441-d92c-4746-83fc-40ff7c4cfe37)

Thanks

**Comment by lukasalexanderweber** [comment]
import cv2 as cv
cv_grid = grid.astype("uint8") * 255
contours, _ = \
    cv.findContours(cv_grid, cv.RETR_TREE, cv.CHAIN_APPROX_NONE)
contour = contours[0][:, 0, :]
lir.lir(grid, contour)

**Comment by srini8080** [comment]
how do I open the image and how do I get the co-ordinates of the rectangle, width and height
Thanks,
    On Saturday, February 24, 2024 at 08:46:34 PM GMT+5:30, Lukas Weber ***@***.***> wrote:  
 
 


import cv2 as cv
cv_grid = grid.astype("uint8") * 255
contours, _ = 
cv.findContours(cv_grid, cv.RETR_TREE, cv.CHAIN_APPROX_NONE)
contour = contours[0][:, 0, :]
lir.lir(grid, contour)

**Comment by lukasalexanderweber** [comment]
```
grid = cv.imread("path/to/img.png", 0)
grid = grid > 0
rect = lir.largest_interior_rectangle(grid)
```
