### ISSUE TITLE
Will you release the source code for lir_within_outline？

### ISSUE THREAD

**Issue by orange-cai** [OpenStitching/lir#32]
hi,I'm interested in your project. He's a great help to me.Will you release the source code for lir_within_outline

**Comment by lukasalexanderweber** [comment]
It has another name in the readme as in the code. In the code it's [lir_within_contour](https://github.com/OpenStitching/lir/blob/main/largestinteriorrectangle/lir_within_contour.py)

**Comment by orange-cai** [comment]
> It has another name in the readme as in the code. In the code it's [lir_within_contour](https://github.com/OpenStitching/lir/blob/main/largestinteriorrectangle/lir_within_contour.py)

Thanks,  really appreciate your reply.
